root = "."
tmp_dir = "tmp"

[build]
cmd = "go generate ./... && go build -o ./tmp/main ."
bin = "./tmp/main"
# Если ваше приложение использует переменные окружения
full_bin = "HOST=0.0.0.0 PORT=9026 ./tmp/main"
include_ext = ["go", "tpl", "tmpl", "html", "graphql"]
exclude_dir = ["assets", "tmp", "vendor"]
exclude_file = []
include_dir = [
    "api",
    "ctxkeys",
    "database",
    "docs",
    "ent/schema",
    "handlers",
    "locales/build",
    "middleware",
    "server",
    "services",
    "types",
    "utils",
]
delay = 2000
stop_on_error = true
send_interrupt = false
kill_delay = "0.5s"

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
