// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"context"
	"main/ent/schema"
	"main/ent/tenant"
	"time"

	"github.com/google/uuid"

	"entgo.io/ent"
	"entgo.io/ent/privacy"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	tenantMixin := schema.Tenant{}.Mixin()
	tenant.Policy = privacy.NewPolicies(schema.Tenant{})
	tenant.Hooks[0] = func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if err := tenant.Policy.EvalMutation(ctx, m); err != nil {
				return nil, err
			}
			return next.Mutate(ctx, m)
		})
	}
	tenantMixinHooks1 := tenantMixin[1].Hooks()

	tenant.Hooks[1] = tenantMixinHooks1[0]
	tenantMixinInters2 := tenantMixin[2].Interceptors()
	tenantMixinInters3 := tenantMixin[3].Interceptors()
	tenant.Interceptors[0] = tenantMixinInters2[0]
	tenant.Interceptors[1] = tenantMixinInters3[0]
	tenantMixinFields0 := tenantMixin[0].Fields()
	_ = tenantMixinFields0
	tenantFields := schema.Tenant{}.Fields()
	_ = tenantFields
	// tenantDescCreateTime is the schema descriptor for create_time field.
	tenantDescCreateTime := tenantMixinFields0[0].Descriptor()
	// tenant.DefaultCreateTime holds the default value on creation for the create_time field.
	tenant.DefaultCreateTime = tenantDescCreateTime.Default.(func() time.Time)
	// tenantDescUpdateTime is the schema descriptor for update_time field.
	tenantDescUpdateTime := tenantMixinFields0[1].Descriptor()
	// tenant.DefaultUpdateTime holds the default value on creation for the update_time field.
	tenant.DefaultUpdateTime = tenantDescUpdateTime.Default.(func() time.Time)
	// tenant.UpdateDefaultUpdateTime holds the default value on update for the update_time field.
	tenant.UpdateDefaultUpdateTime = tenantDescUpdateTime.UpdateDefault.(func() time.Time)
	// tenantDescID is the schema descriptor for id field.
	tenantDescID := tenantFields[0].Descriptor()
	// tenant.DefaultID holds the default value on creation for the id field.
	tenant.DefaultID = tenantDescID.Default.(func() uuid.UUID)
}

const (
	Version = "v0.14.5"                                         // Version of ent codegen.
	Sum     = "h1:Rj2WOYJtCkWyFo6a+5wB3EfBRP0rnx1fMk6gGA0UUe4=" // Sum of ent codegen.
)
