package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"
	"main/ent"
)

// User is the resolver for the user field.
func (r *fileResolver) User(ctx context.Context, obj *ent.File) (*ent.User, error) {
	// Return a stub User entity with the user ID from TicketWorkTime
	// The actual User data will be resolved by the auth service in the federation
	return &ent.User{
		ID: obj.CreatedBy,
	}, nil
}
