package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.73

import (
	"context"
	"main/ent"
	entfile "main/ent/file"
	"main/graph/dataloader"
	"main/graph/model"
	fileservice "main/services/file"
	"main/utils"

	"entgo.io/contrib/entgql"
	"github.com/google/uuid"
	"go.uber.org/zap"
)

// UploadFile is the resolver for the uploadFile field.
func (r *mutationResolver) UploadFile(ctx context.Context, input model.UploadFileInput) (*model.FileUploadResponse, error) {
	client := r.getClient(ctx)

	// 🔒 [PERMISSION CHECK] Проверяем права на загрузку файлов
	fileService := fileservice.NewFileService()
	if err := fileService.CanUploadFile(ctx); err != nil {
		return &model.FileUploadResponse{
			Success: false,
			Message: err.Error(),
			File:    nil,
		}, nil
	}

	// Валидируем, что файл был передан
	if input.File.Filename == "" {
		return &model.FileUploadResponse{
			Success: false,
			Message: utils.T(ctx, "error.file.no_file"),
			File:    nil,
		}, nil
	}

	// Логируем информацию о загружаемом файле
	utils.Logger.Info("File upload attempt",
		zap.String("filename", input.File.Filename),
		zap.Int64("size", input.File.Size),
		zap.String("content_type", input.File.ContentType))

	// Дополнительная проверка размера файла
	const maxFileSize = 100 * 1024 * 1024 // 100MB
	if input.File.Size > maxFileSize {
		utils.Logger.Warn("File too large",
			zap.String("filename", input.File.Filename),
			zap.Int64("size", input.File.Size),
			zap.Int64("max_size", maxFileSize))
		return &model.FileUploadResponse{
			Success: false,
			Message: utils.T(ctx, "error.file.too_large"),
			File:    nil,
		}, nil
	}

	// Создаем input для файлового сервиса
	fileInput := fileservice.UploadFileInput{
		Upload:      &input.File,
		Description: input.Description,
	}

	// Используем сервис для загрузки файла
	fileResult, err := fileService.UploadFile(ctx, client, fileInput)
	if err != nil {
		utils.Logger.Error("Failed to upload file",
			zap.Error(err),
			zap.String("filename", input.File.Filename))
		return &model.FileUploadResponse{
			Success: false,
			Message: err.Error(),
			File:    nil,
		}, nil
	}

	return &model.FileUploadResponse{
		Success: true,
		Message: utils.T(ctx, "success.file.uploaded"),
		File:    fileResult,
	}, nil
}

// UpdateFileInfo is the resolver for the updateFileInfo field.
func (r *mutationResolver) UpdateFileInfo(ctx context.Context, id uuid.UUID, input model.UpdateFileInfoInput) (*model.FileResponse, error) {
	client := r.getClient(ctx)

	// 🔒 [PERMISSION CHECK] Проверяем права на обновление файла
	fileService := fileservice.NewFileService()
	if err := fileService.CanUpdateFile(ctx, client, id); err != nil {
		return &model.FileResponse{
			Success: false,
			Message: err.Error(),
			File:    nil,
		}, nil
	}

	// Создаем updater
	updater := client.File.UpdateOneID(id)

	// Обновляем только переданные поля
	if input.Description != nil {
		updater = updater.SetDescription(*input.Description)
	}
	if input.OriginalName != nil {
		updater = updater.SetOriginalName(*input.OriginalName)
	}

	// Выполняем обновление
	ctxWithClient := ent.NewContext(ctx, client)
	updatedFile, err := updater.Save(ctxWithClient)
	if err != nil {
		if ent.IsNotFound(err) {
			return &model.FileResponse{
				Success: false,
				Message: utils.T(ctx, "error.file.not_found"),
				File:    nil,
			}, nil
		}
		utils.Logger.Error("Failed to update file", zap.Error(err), zap.String("file_id", id.String()))
		return &model.FileResponse{
			Success: false,
			Message: utils.T(ctx, "error.file.update_failed"),
			File:    nil,
		}, nil
	}

	return &model.FileResponse{
		Success: true,
		Message: utils.T(ctx, "success.file.updated"),
		File:    updatedFile,
	}, nil
}

// DeleteFile is the resolver for the deleteFile field.
func (r *mutationResolver) DeleteFile(ctx context.Context, id uuid.UUID) (*model.FileDeleteResponse, error) {
	client := r.getClient(ctx)

	// 🔒 [PERMISSION CHECK]
	fileService := fileservice.NewFileService()
	if err := fileService.CanDeleteFile(ctx, client, id); err != nil {
		return &model.FileDeleteResponse{Success: false, Message: err.Error()}, nil
	}

	// 🔄 [TRANSACTION]
	tx, err := client.Tx(ctx)
	if err != nil {
		return &model.FileDeleteResponse{Success: false, Message: utils.T(ctx, "error.transaction.failed")}, nil
	}
	defer func() {
		if err != nil {
			_ = tx.Rollback()
		}
	}()

	txCtx := ent.NewTxContext(ctx, tx)

	// Удаляем файл через сервис (включает удаление из S3 и БД)
	if err = fileService.DeleteFile(txCtx, tx.Client(), id); err != nil {
		utils.Logger.Error("Failed to delete file", zap.Error(err), zap.String("file_id", id.String()))
		return &model.FileDeleteResponse{Success: false, Message: err.Error()}, nil
	}

	if err = tx.Commit(); err != nil {
		return &model.FileDeleteResponse{Success: false, Message: utils.T(ctx, "error.transaction.commit_failed")}, nil
	}

	return &model.FileDeleteResponse{Success: true, Message: utils.T(ctx, "success.file.deleted")}, nil
}

// File is the resolver for the file field.
func (r *queryResolver) File(ctx context.Context, id uuid.UUID) (*model.FileResponse, error) {
	client := r.getClient(ctx)

	// 🔒 [PERMISSION CHECK] Проверяем права на просмотр файла
	fileService := fileservice.NewFileService()
	if err := fileService.CanViewFile(ctx, client, id); err != nil {
		return &model.FileResponse{
			Success: false,
			Message: err.Error(),
			File:    nil,
		}, nil
	}

	// Получаем детали файла
	file, err := client.File.Query().
		Where(entfile.ID(id)).
		Only(ctx)

	if err != nil {
		if ent.IsNotFound(err) {
			return &model.FileResponse{
				Success: false,
				Message: utils.T(ctx, "error.file.not_found"),
				File:    nil,
			}, nil
		}
		return &model.FileResponse{
			Success: false,
			Message: utils.T(ctx, "error.file.get_failed"),
			File:    nil,
		}, nil
	}

	return &model.FileResponse{
		Success: true,
		Message: utils.T(ctx, "success.file.found"),
		File:    file,
	}, nil
}

// Files is the resolver for the files field.
func (r *queryResolver) Files(ctx context.Context, after *entgql.Cursor[uuid.UUID], first *int, before *entgql.Cursor[uuid.UUID], last *int, orderBy []*ent.FileOrder, where *ent.FileWhereInput) (*ent.FileConnection, error) {
	client := r.getClient(ctx)

	// Для списка файлов проверяем только базовую аутентификацию
	// Конкретные права проверяются на уровне каждого файла

	// Создаем запрос для получения файлов
	query := client.File.Query()

	// Применяем CollectFields для оптимизации
	query, err := query.CollectFields(ctx)
	if err != nil {
		return nil, err
	}

	// Возвращаем пагинированный результат
	return query.Paginate(ctx, after, first, before, last,
		ent.WithFileFilter(where.Filter),
		ent.WithFileOrder(orderBy),
	)
}

// FileList is the resolver for the fileList field.
func (r *queryResolver) FileList(ctx context.Context, after *entgql.Cursor[uuid.UUID], first *int, before *entgql.Cursor[uuid.UUID], last *int, orderBy []*ent.FileOrder, where *ent.FileWhereInput) (*ent.FileConnection, error) {
	client := r.getClient(ctx)

	// Для списка файлов проверяем только базовую аутентификацию
	// Конкретные права проверяются на уровне каждого файла

	// Создаем запрос для получения файлов
	query := client.File.Query()

	// Применяем CollectFields для оптимизации
	query, err := query.CollectFields(ctx)
	if err != nil {
		return nil, err
	}

	// Возвращаем пагинированный результат
	return query.Paginate(ctx, after, first, before, last,
		ent.WithFileFilter(where.Filter),
		ent.WithFileOrder(orderBy),
	)
}

// FilesByUser is the resolver for the filesByUser field.
func (r *queryResolver) FilesByUser(ctx context.Context, userID uuid.UUID, limit *int, offset *int) (*model.FileListResponse, error) {
	client := r.getClient(ctx)

	// Устанавливаем значения по умолчанию
	limitValue := 20
	offsetValue := 0

	if limit != nil && *limit > 0 {
		limitValue = *limit
	}
	if offset != nil && *offset >= 0 {
		offsetValue = *offset
	}

	// Получаем файлы пользователя через сервис
	fileService := fileservice.NewFileService()
	files, err := fileService.GetFilesByUser(ctx, client, userID, limitValue, offsetValue)
	if err != nil {
		utils.Logger.Error("Failed to get files by user",
			zap.Error(err),
			zap.String("user_id", userID.String()))
		return &model.FileListResponse{
			Success:    false,
			Message:    err.Error(),
			Files:      []*ent.File{},
			TotalCount: 0,
		}, nil
	}

	// Подсчитываем общее количество файлов пользователя
	// Используем простой подсчет на основе полученных файлов как fallback
	totalCount := len(files)

	return &model.FileListResponse{
		Success:    true,
		Message:    utils.T(ctx, "success.files.found"),
		Files:      files,
		TotalCount: totalCount,
	}, nil
}

// GetFileDownloadURL is the resolver for the getFileDownloadURL field.
func (r *mutationResolver) GetFileDownloadURL(ctx context.Context, id uuid.UUID) (*model.FileDownloadURLResponse, error) {
	client := r.getClient(ctx)

	// Получаем pre-signed URL для файла через сервис
	fileService := fileservice.NewFileService()
	result, err := fileService.GetFileDownloadURL(ctx, client, id)
	if err != nil {
		utils.Logger.Error("Failed to get file download URL",
			zap.Error(err),
			zap.String("file_id", id.String()))
		return &model.FileDownloadURLResponse{
			Success: false,
			Message: err.Error(),
			URL:     nil,
		}, nil
	}

	return &model.FileDownloadURLResponse{
		Success:   true,
		Message:   utils.T(ctx, "success.file.download_url_generated"),
		URL:       &result.URL,
		ExpiresAt: &result.ExpiresAt,
	}, nil
}

// GetBatchDownloadURL is the resolver for the getBatchDownloadURL field.
func (r *mutationResolver) GetBatchDownloadURL(ctx context.Context, input model.BatchDownloadInput) (*model.BatchDownloadURLResponse, error) {
	client := r.getClient(ctx)

	// FileIds уже являются []uuid.UUID, поэтому преобразование не нужно
	fileIDs := input.FileIds

	// Получаем архивное имя (может быть пустым)
	var archiveName string
	if input.ArchiveName != nil {
		archiveName = *input.ArchiveName
	}

	// Получаем pre-signed URL для архива через сервис
	fileService := fileservice.NewFileService()
	result, err := fileService.GetBatchDownloadURL(ctx, client, fileIDs, archiveName)
	if err != nil {
		utils.Logger.Error("Failed to get batch download URL",
			zap.Error(err),
			zap.Int("file_count", len(fileIDs)))
		return &model.BatchDownloadURLResponse{
			Success:    false,
			Message:    err.Error(),
			TotalFiles: 0,
		}, nil
	}

	return &model.BatchDownloadURLResponse{
		Success:     true,
		Message:     utils.T(ctx, "success.file.batch_download_url_generated"),
		URL:         &result.URL,
		ExpiresAt:   &result.ExpiresAt,
		ArchiveName: &result.ArchiveName,
		TotalFiles:  result.TotalFiles,
	}, nil
}

// CanDelete is the resolver for the canDelete field on File.
func (r *fileResolver) CanDelete(ctx context.Context, obj *ent.File) (bool, error) {
	return dataloader.GetFileCanDelete(ctx, obj.ID)
}
