// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// DeletemeColumns holds the columns for the "deleteme" table.
	DeletemeColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "create_time", Type: field.TypeTime},
		{Name: "update_time", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeUUID, Nullable: true},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// DeletemeTable holds the schema information for the "deleteme" table.
	DeletemeTable = &schema.Table{
		Name:       "deleteme",
		Columns:    DeletemeColumns,
		PrimaryKey: []*schema.Column{DeletemeColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		DeletemeTable,
	}
)

func init() {
	DeletemeTable.Annotation = &entsql.Annotation{
		Table: "deleteme",
	}
}
